### ISSUE TITLE
unpredictable timeouts executing CLI commands

### ISSUE THREAD

**Issue by itewk** [cpitman/puppet-jboss_admin#41]
I don't know why, but sometimes when puppet runs it gets timeouts trying to run certain CLI commands. run puppet again and everything works. is there a timeout parameter we can ajust when making calls to the CLI?

```
Info: /Stage[main]/Jboss::Cleanup/Jboss_admin::Cleanup[Post Configuration, Pre Deployment]/Jboss_exec[Reload Server Post Configuration, Pre Deployment]: Scheduling refresh of Jboss_exec[Check Server Up After Post Configuration, Pre Deployment]
Error: /Stage[main]/Jboss::Cleanup/Jboss_admin::Cleanup[Post Configuration, Pre Deployment]/Jboss_exec[Restart Server Post Configuration, Pre Deployment]: Could not evaluate: 399: unexpected token at 'org.jboss.as.cli.CliInitializationException: Failed to connect to the controller	at org.jboss.as.cli.impl.CliLauncher.initCommandContext(CliLauncher.java:280)
at org.jboss.as.cli.impl.CliLauncher.main(CliLauncher.java:240)
at org.jboss.as.cli.CommandLineMain.main(CommandLineMain.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.jboss.modules.Module.run(Module.java:270)
at org.jboss.modules.Main.main(Main.java:411)Caused by: org.jboss.as.cli.CommandLineException: The controller is not available at eti-eap-10.pvt.uspto.gov:9999
at org.jboss.as.cli.impl.CommandContextImpl.tryConnection(CommandContextImpl.java:951)
at org.jboss.as.cli.impl.CommandContextImpl.connectController(CommandContextImpl.java:790)
at org.jboss.as.cli.impl.CommandContextImpl.connectController(CommandContextImpl.java:766)
at org.jboss.as.cli.impl.CliLauncher.initCommandContext(CliLauncher.java:278)	... 8 moreCaused by: java.io.IOException: java.net.ConnectException: JBAS012144: Could not connect to remote://eti-eap-10.pvt.uspto.gov:9999. The connection timed out	at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeForResult(AbstractModelControllerClient.java:129)
at org.jboss.as.controller.client.impl.AbstractModelControllerClient.execute(AbstractModelControllerClient.java:71)
at org.jboss.as.cli.impl.CommandContextImpl.tryConnection(CommandContextImpl.java:929)	... 11 moreCaused by: java.net.ConnectException: JBAS012144: Could not connect to remote://eti-eap-10.pvt.uspto.gov:9999. The connection timed out	at org.jboss.as.protocol.ProtocolConnectionUtils.connectSync(ProtocolConnectionUtils.java:131)
at org.jboss.as.protocol.ProtocolConnectionManager$EstablishingConnection.connect(ProtocolConnectionManager.java:256)
at org.jboss.as.protocol.ProtocolConnectionManager.connect(ProtocolConnectionManager.java:70)	at org.jboss.as.protocol.mgmt.FutureManagementChannel$Establishing.getChannel(FutureManagementChannel.java:176)
at org.jboss.as.cli.impl.CLIModelControllerClient.getOrCreateChannel(CLIModelControllerClient.java:155)
at org.jboss.as.cli.impl.CLIModelControllerClient$2.getChannel(CLIModelControllerClient.java:117)	at org.jboss.as.protocol.mgmt.ManagementChannelHandler.executeRequest(ManagementChannelHandler.java:115)
at org.jboss.as.protocol.mgmt.ManagementChannelHandler.executeRequest(ManagementChannelHandler.java:90)
at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeRequest(AbstractModelControllerClient.java:236)
at org.jboss.as.controller.client.impl.AbstractModelControllerClient.execute(AbstractModelControllerClient.java:141)
at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeForResult(AbstractModelControllerClient.java:127)	... 13 more]'
```

**Comment by itewk** [comment]
i am going to close this until such time as I have any more concrete actionable info.
